#COLOR PRIMARIO PARA LOS TITULOS DE LAS PANTALLAS
ENCABEZADO_COLOR_PRIMARIO = "#2C3E50"

#COLOR DE LOS BOTONES DE LA PANTALLA PRINCIPAL DE ACCIONES Y BOTON RECARGA Y ATRAS DE VENTAS SECUNDARIAS
BOTONES_ACCIONES = "#2C3E50"
BOTONES_ACCIONES_HOVER = "#34495E"
BOTONES_ACCIONES_PRESSED = "#1ABC9C"

#COLOR DE FONDO DE LAS TARJETAS
GRADIENTE_INICIO = "#2C3E50"
GRADIENTE_FINAL = "#34495E"

